### PR TITLE
Make nested disable/enable_irq work

### PR DESCRIPTION
**Pull request by mmoskal**
@jamesadevine @finneyj  what do you think?

### CODE REVIEW

**Comment by jamesadevine** [comment]
It looks good to me. I think we do want this behaviour as often there are multiple critical paths coinciding ([for instance with the Timer](https://github.com/lancaster-university/codal-stm32/blob/master/src/ZTimer.cpp#L55)). 

What's your motivating use case Michal, similar to the timer code above?

**Comment by mmoskal** [comment]
`DMESG()` disables interrupts, so you cannot use it to log inside of critical section (which normally you shouldn't, but sometimes you want temporarily).

**Comment by mmoskal** [comment]
Also, I think we should do this for all codal targets - this is much less error prone than the current solution.

**Comment by jamesadevine** [comment]
Agree!

**Pull request merged**
